language: node_js
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
sudo: false
env:
  MYSQL_DATABASE: 'lambdadb_test'
  MYSQL_USER: 'root'
  MYSQL_PORT: 3306
  MYSQL_PASSWORD: 
  MYSQL_HOST: '127.0.0.1'
  NODE_ENV: 'travis'
  SECRET_TOKEN: 'travis_test'
node_js:
- '6'
services:
- mysql
install:
- npm install
- npm install --dev
before_script:
- mysql -e 'create database lambdadb_test;'
script:
- NODE_ENV='travis' npm test
